-- SQL schema for email_verification_requests

CREATE TABLE IF NOT EXISTS public.email_verification_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid,
  email text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz,
  verified_by text
);

CREATE INDEX IF NOT EXISTS idx_email_verification_requests_email ON public.email_verification_requests (email);
CREATE INDEX IF NOT EXISTS idx_email_verification_requests_status ON public.email_verification_requests (status);
