-- Run this in your Supabase SQL editor to create the support_tickets table and storage bucket

-- Create table
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  full_name text,
  email text,
  subject text,
  category text,
  message text,
  screenshot_url text,
  status text default 'Open',
  admin_reply text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Optional: create storage bucket named 'support-screenshots' using Supabase UI or via API
-- Note: ensure the bucket has public access disabled if you prefer private storage and use signed URLs.
